import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const inter = localFont({
  src: [
    {
      path: "./assets/fonts/Inter_28pt-Regular.ttf",
      weight: "400",
    },
    {
      path: "./assets/fonts/Inter_28pt-Medium.ttf",
      weight: "500",
    },
    {
      path: "./assets/fonts/Inter_28pt-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "./assets/fonts/Inter_28pt-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-inter",
});

const sora = localFont({
  src: "./assets/fonts/Sora-SemiBold.ttf",
  variable: "--font-sora",
  weight: "600",
});

const poppins = localFont({
  src: "./assets/fonts/Poppins-Regular.ttf",
  variable: "--font-poppins",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${sora.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
